# Generated by Django 2.2.4 on 2019-08-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Term', '0001_initial'),
    ]


    def insert_default_terms(apps,schema_editor):
        Term=apps.get_model('Term','Term')
        term= Term(details='Edit Me')
        term.save()


    operations = [
        migrations.RunPython(insert_default_terms),
    ]


    
